version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: pagos
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      MYSQL_ROOT_PASSWORD: devpass
    volumes:
      - ./BD/:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    
  web:
    build: .
    image: php:7.3.3-apache
    container_name: docker-phpd
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    links:
      - mysql