version: "3.9"
services:
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: pagos
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./BD:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - meko_estebanquito
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./:/var/www/html/
        depends_on:
            - db
        networks:
            - meko_estebanquito
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
networks:
    meko_estebanquito:
volumes:
    persistent:
