version: "3.9"
services:
    php-micro:
        container_name: php-micro
        build: 
            context: .
        restart: always
        volumes: 
            -   type: bind
                source: ./src
                target: /app/src
    apache-micro:
        container_name: apache-micro
        image: httpd:2.4-alpine
        ports: 
            - 80:80
        restart: always
        volumes: 
            -   type: bind
                source: ./src
                target: /app/src
            -   type: bind
                source: ./src/httpd.conf
                target: /usr/local/apache2/conf/httpd.conf
    db-micro:
        container_name: db-micro
        image: mysql:5.7
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: pagos
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes: 
            -   type: volume
                source: db_persistent_data
                target: /var/lib/mysql 
                volume:
                    nocopy: true
volumes: 
    db_persistent_data:
        driver: local
