version: '3.3'
services:
  web:
    buid:
      context: ./
    container_name: php73
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 8008:80
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pagos
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - 6033:3306